using Test

include("test_utils.jl")

@testset "BigFloatLinearAlgebra" begin
    include("ownership.jl")
    include("level1.jl")
    include("level2.jl")
    include("level3.jl")
    include("triangular.jl")
    include("cholesky.jl")
    include("failure_semantics.jl")
    include("precision.jl")
    include("concurrency.jl")
    include("mpfr.jl")
    include("property.jl")
    include("workspace.jl")
    include("blocked.jl")
    include("threading.jl")
    include("symmetric.jl")
    include("ldlt.jl")
    include("qr.jl")
    include("quality.jl")
    include("lu.jl")
    include("repeated_solve.jl")
    include("caches.jl")
    include("qdldl_extension.jl")
    include("malformed_factor_fuzz.jl")
    include("factor_shape_integrity.jl")
    include("cache_allocating_solve.jl")
    include("rrqr_integrity.jl")
    include("factor_accessor_integrity.jl")
    include("cache_prepare_contract.jl")
    include("malformed_factor_shape_fuzz.jl")
    include("malformed_factor_semantic_fuzz.jl")
    include("cholesky_semantic_integrity.jl")
    include("cache_trusted_precision.jl")
    include("numerical_robustness.jl")
    include("final_review_regressions.jl")
    include("linearsolve_ext.jl")
end
